service: serverless-repository-manager

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - 'arn:aws:s3:::perfecto-repository-${opt:stage}-${self:custom.region}*'

custom:
  region: ${opt:region, self:provider.region}

functions:
  getUploadLink:
    handler: handlers/getUploadLink.handle
    events:
      - http:
          path: uploadlink/{id+}
          method: get
    environment:
      BUCKET_NAME: perfecto-repository-${opt:stage}-${self:custom.region}
    # Example for using a layer  
    # layers:
    #  - 'arn:aws:lambda:us-east-1:961701920393:layer:keycloakAuth:2'