service: serverless-rest-api-with-dynamodb

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getUploadLink:
    handler: handlers/getUploadLink.handle
    events:
      - http:
          path: uploadlink/{id}
          method: get
    environment:
      BUCKET_NAME: perfecto-repository-${opt:stage}-${self:custom.region}