AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    repository-manager

    Sample SAM Template for sam-app
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3

Parameters: 
  Env: 
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - staging
      - production
    Description: The environment to deploy the applicaton in.

Resources:

    GetUploadLinkFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: .
            Handler: handlers/getUploadLink.handle
            Runtime: nodejs8.10
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    BUCKET_NAME: perfecto-repository-${Ref:Env}-${AWS::Region}
            Events:
                GetUploadLink:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: uploadlink/{id+}
                        Method: get

Outputs:

    GetUploadLinkApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    GetUploadLinkFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt GetUploadLinkFunction.Arn

    GetUploadLinkFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt GetUploadLinkFunctionRole.Arn
